name: Autoupdate pre-commit configs and tflint aws plugin

on:
  # every sunday at midnight
  schedule:
    - cron: "0 0 * * 0"
  # on demand
  workflow_dispatch:

# Request from Org admin to allow Github Action workflow to make PR under Settings > Actions > General
permissions:
  actions: read
  checks: read
  contents: write #require this to write to repo
  pull-requests: write #require this to create PR

jobs:
  auto-update:
    runs-on: ubuntu-latest
    steps:
      - uses: SPHTech-Platform/gha-pre-commit-autoupdate@63fd59b2635b958b4128ba1f3b6859984b04ff47 # v1.1.1
        name: Update pre-commit config automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: SPHTech-Platform/gha-tflint-aws-plugin-autoupdate@a098bc733ce612aa57f9ce1a1a384e0c6abf180c # v0.1.0
        name: Update tflint plugin automatically
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
